 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chinese_foods", type: :request do
  
  # ChineseFood. As you add validations to ChineseFood, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChineseFood.create! valid_attributes
      get chinese_foods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chinese_food = ChineseFood.create! valid_attributes
      get chinese_food_url(chinese_food)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chinese_food_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chinese_food = ChineseFood.create! valid_attributes
      get edit_chinese_food_url(chinese_food)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChineseFood" do
        expect {
          post chinese_foods_url, params: { chinese_food: valid_attributes }
        }.to change(ChineseFood, :count).by(1)
      end

      it "redirects to the created chinese_food" do
        post chinese_foods_url, params: { chinese_food: valid_attributes }
        expect(response).to redirect_to(chinese_food_url(ChineseFood.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChineseFood" do
        expect {
          post chinese_foods_url, params: { chinese_food: invalid_attributes }
        }.to change(ChineseFood, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chinese_foods_url, params: { chinese_food: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chinese_food" do
        chinese_food = ChineseFood.create! valid_attributes
        patch chinese_food_url(chinese_food), params: { chinese_food: new_attributes }
        chinese_food.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chinese_food" do
        chinese_food = ChineseFood.create! valid_attributes
        patch chinese_food_url(chinese_food), params: { chinese_food: new_attributes }
        chinese_food.reload
        expect(response).to redirect_to(chinese_food_url(chinese_food))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chinese_food = ChineseFood.create! valid_attributes
        patch chinese_food_url(chinese_food), params: { chinese_food: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chinese_food" do
      chinese_food = ChineseFood.create! valid_attributes
      expect {
        delete chinese_food_url(chinese_food)
      }.to change(ChineseFood, :count).by(-1)
    end

    it "redirects to the chinese_foods list" do
      chinese_food = ChineseFood.create! valid_attributes
      delete chinese_food_url(chinese_food)
      expect(response).to redirect_to(chinese_foods_url)
    end
  end
end
