 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/japanese_foods", type: :request do
  
  # JapaneseFood. As you add validations to JapaneseFood, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JapaneseFood.create! valid_attributes
      get japanese_foods_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      japanese_food = JapaneseFood.create! valid_attributes
      get japanese_food_url(japanese_food)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_japanese_food_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      japanese_food = JapaneseFood.create! valid_attributes
      get edit_japanese_food_url(japanese_food)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JapaneseFood" do
        expect {
          post japanese_foods_url, params: { japanese_food: valid_attributes }
        }.to change(JapaneseFood, :count).by(1)
      end

      it "redirects to the created japanese_food" do
        post japanese_foods_url, params: { japanese_food: valid_attributes }
        expect(response).to redirect_to(japanese_food_url(JapaneseFood.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JapaneseFood" do
        expect {
          post japanese_foods_url, params: { japanese_food: invalid_attributes }
        }.to change(JapaneseFood, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post japanese_foods_url, params: { japanese_food: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested japanese_food" do
        japanese_food = JapaneseFood.create! valid_attributes
        patch japanese_food_url(japanese_food), params: { japanese_food: new_attributes }
        japanese_food.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the japanese_food" do
        japanese_food = JapaneseFood.create! valid_attributes
        patch japanese_food_url(japanese_food), params: { japanese_food: new_attributes }
        japanese_food.reload
        expect(response).to redirect_to(japanese_food_url(japanese_food))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        japanese_food = JapaneseFood.create! valid_attributes
        patch japanese_food_url(japanese_food), params: { japanese_food: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested japanese_food" do
      japanese_food = JapaneseFood.create! valid_attributes
      expect {
        delete japanese_food_url(japanese_food)
      }.to change(JapaneseFood, :count).by(-1)
    end

    it "redirects to the japanese_foods list" do
      japanese_food = JapaneseFood.create! valid_attributes
      delete japanese_food_url(japanese_food)
      expect(response).to redirect_to(japanese_foods_url)
    end
  end
end
